# Generated by Django 4.0.2 on 2022-02-23 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_url_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uri',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
