# Generated by Django 4.0.2 on 2022-02-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_url_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
